**In these notebook we clearly understand about numpy and practice some codes with it**

NumPy (Numerical Python) is a Python library that adds support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. NumPy is open-source software and has many contributors. NumPy is a NumFOCUS fiscally sponsored project

we can perform large number of numerical operation using numpy

In [18]:
import numpy as np
import warnings 
warnings.filterwarnings('ignore')

In [5]:
lis=[1,2,3,4,5]

In [6]:
type(lis)

list

In [8]:
arr = np.array(lis)
type(arr)

numpy.ndarray

In [9]:
arr.shape

(5,)

In [10]:
np.random.randint(0,100,8) #randomly generating 8 values between 0 to 100

array([60, 32, 66, 39, 11, 86, 14, 29])

In [13]:
np.random.random_sample(5)

array([0.40560882, 0.63315928, 0.64086914, 0.76299973, 0.97687529])

In [14]:
np.random.randn(5,4) #return sample from standard normal distribution

array([[ 1.65034933, -0.5494913 , -0.68644086,  1.06320179],
       [ 0.57545633, -0.96112671,  0.33678402,  0.57388084],
       [ 1.05142803, -0.01083931,  0.72652699, -0.05937214],
       [ 0.06271438, -0.99910628, -1.91822791, -0.98150869],
       [ 0.89286102, -0.24956328, -1.44123018, -0.76900208]])

In [24]:
a=np.random.rand(3,4) #random samples from a uniform distribution

In [25]:
a

array([[9.25854916e-01, 5.94924574e-01, 1.25792699e-04, 1.54667084e-01],
       [1.98321576e-01, 6.83326396e-01, 3.38633892e-01, 6.87412040e-01],
       [3.98049979e-01, 1.85656397e-01, 2.66718480e-01, 7.84784724e-01]])

In [26]:
a.shape

(3, 4)

In [27]:
#reshaping an array
a.reshape(4,3)

array([[9.25854916e-01, 5.94924574e-01, 1.25792699e-04],
       [1.54667084e-01, 1.98321576e-01, 6.83326396e-01],
       [3.38633892e-01, 6.87412040e-01, 3.98049979e-01],
       [1.85656397e-01, 2.66718480e-01, 7.84784724e-01]])

In [19]:
#multi-nested array
arr1=[1,2,3,4,5]
arr2=[5,6,7,8,9]
arr3=[10,11,12,13,14,15]
arr=np.array([arr1,arr2,arr3])
print(arr)

[list([1, 2, 3, 4, 5]) list([5, 6, 7, 8, 9])
 list([10, 11, 12, 13, 14, 15])]


In [20]:
arr.shape

(3,)

In [35]:
arr3=[10,11,12,13,14,15]
c=np.array(arr3)

In [36]:
#accessing array elements
c

array([10, 11, 12, 13, 14, 15])

In [39]:
c[3:]

array([13, 14, 15])

In [41]:
c[:-3]

array([10, 11, 12])

In [42]:
#changing the array elements with 100
c[3:]=100

In [43]:
c

array([ 10,  11,  12, 100, 100, 100])

In [49]:
arr=np.zeros(100).reshape(10,10)
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [50]:
arr1=np.ones(100).reshape(10,10)
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [54]:
arr2=np.eye(10)
arr2

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [56]:
np.empty((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [57]:
np.full((3,2),0)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [61]:
np.float((1.2))

1.2

**let's see some mathematical operations using numpy**

In [65]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
c=a*2
c

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [67]:
b=a**2
b

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [68]:
d=a+2
d

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
np.minimum(a,b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
np.maximum(a,b)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [74]:
a=np.arange(0,30,2).reshape(3,5)
a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [77]:
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.dtype.name)
print(type(a))
print(a.itemsize)

(3, 5)
int32
2
15
int32
<class 'numpy.ndarray'>
4


In [78]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [79]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [80]:
np.linspace(0, 2, 9)                   # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [83]:
arr1=np.ones(15).reshape(3,5)
arr1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [84]:
arr1.transpose()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])